version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ufc_picks_test
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d ufc_picks_test"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
